# Cloudflare Pages configuration
# https://developers.cloudflare.com/pages/configuration/wrangler-configuration/

name = "tanchao-xyz"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[env.production]
name = "tanchao-xyz"
