#!/usr/bin/env bash
#
# sync-substack-local.sh — daily Substack sync, intended for launchd on Mac.
#
# Why local: Substack sits behind Cloudflare bot management, which blocks
# data-center IPs (GH Actions runners, CF Workers). Running from a Mac on
# home Wi-Fi side-steps that entirely. See git history for the GH-Actions-
# based attempts that didn't pan out.
#
# Branch protection on `main` blocks direct push, so this script pushes a
# branch and opens an auto-merge PR. CI ("build") gates the merge.
#
# Setup: clone the repo to a dedicated path (e.g. ~/.cache/tanchao-substack-sync),
# install deps once with `npm ci`, then point launchd at this script. The
# script refuses to run unless the working tree is clean and on `main`, so
# it won't clobber day-to-day work if you accidentally invoke it elsewhere.

set -euo pipefail

# launchd doesn't load login shells; make tools we need findable.
export PATH="/Users/ctan/.nvm/versions/node/v22.16.0/bin:/opt/homebrew/bin:/usr/bin:/bin"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

log() { printf "%s %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$*"; }

# --- Safety checks --------------------------------------------------------
CURRENT_BRANCH="$(git branch --show-current 2>/dev/null || echo "")"
if [ "$CURRENT_BRANCH" != "main" ]; then
  log "Refusing to run: current branch is '$CURRENT_BRANCH', expected 'main'."
  log "This script is meant to run in a dedicated sync clone, not your dev repo."
  exit 0
fi

if ! git diff --quiet || ! git diff --cached --quiet; then
  log "Refusing to run: working tree is dirty. Commit or stash first."
  exit 0
fi

# --- Refresh ---------------------------------------------------------------
log "Fetching origin/main and resetting…"
git fetch origin main --quiet
git reset --hard origin/main --quiet

if [ ! -d node_modules ]; then
  log "node_modules missing; running npm ci…"
  npm ci --silent
fi

# --- Sync ------------------------------------------------------------------
log "Running npm run sync:substack…"
npm run sync:substack

if git diff --quiet src/content/notes/; then
  log "No new notes. Done."
  exit 0
fi

# --- PR with auto-merge ----------------------------------------------------
DATE="$(date '+%Y-%m-%d')"
BRANCH="chore/sync-substack-$DATE"

log "New notes detected. Creating branch $BRANCH and PR…"
git checkout -B "$BRANCH"
git add src/content/notes/
git -c user.name="substack-sync-bot" \
    -c user.email="bot@tanchao.xyz" \
    commit -m "chore(notes): sync Substack notes ($DATE)"
git push -fu origin "$BRANCH" --quiet

gh pr create \
  --title "chore(notes): sync Substack notes ($DATE)" \
  --body "Auto-generated by the local launchd timer on Chao's Mac." \
  >/dev/null

gh pr merge --auto --squash --delete-branch >/dev/null
log "PR opened with auto-merge enabled. CI will gate the merge."

# Leave the sync clone back on main so the next run starts clean.
git checkout main --quiet
git reset --hard origin/main --quiet
